package com.Google;

import java.util.Objects;

public class Point {
    private int x;
    private int y;

    public Point(int x,int y){
        this.x = x;
        this.y = y;
    }

//    @Override           // point2 object
//    public boolean equals(Object obj) {
//        if(this == obj) return true;
//        if(!(obj instanceof Point)) return false;
//        // obj is belong to Point class - instanceof
//        var other = (Point)obj; // downcasting
//        return other.x == x && other.y == y;
//    }
//
//    // also override hashcode
//    @Override
//    public int hashCode(){
//        return Objects.hash(x, y);
//    }

    // Autogenerated
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Point point = (Point) o;
        return x == point.x && y == point.y;
    }

    @Override
    public int hashCode() {
        return Objects.hash(x, y);
    }
}